### PR TITLE
Allow at rules within a nested block if it's at the max nesting level, Fixes #4

### LINKED ISSUE #4: At-rules within a nested block
We use the BEM naming scheme when creating modules so it's pretty common to see something like this

``` scss
.module {
    padding: 1rem;

    @media (min-width: 50em) {
        padding: 2rem;
    }

    &__element {
        font-size: 1.25rem;

        @media (min-width: 50em) {
            font-size: 2rem;
        }
    }
}
```

Is there a way to allow at-rules within a nested block, but not _another_ element?

``` scss
.module {
    &__element {
        font-size: 1.25rem;

        // Allow this
        @media (min-width: 50em) {
            font-size: 2rem;
        }

        // Disallow this
        &__another-element {
            color: green;
        }
    }
}
```

**Update**: Here's my current .stylelintrc (adjusted for only the relevant rule)

``` json
{
  "plugins": {
    "statement-max-nesting-depth": "stylelint-statement-max-nesting-depth"
  },
  "rules": {
    "statement-max-nesting-depth": [2, 1, { "atRulesDontCount": true }]
  }
}
```

### PR DESCRIPTION
**Pull request by dan-gamble**
First of all this is my 1st ever PR and i'm still very new to the PostCSS ecosystem let alone the Stylelint eco system.

I'm not 100% sure how to get tape working so i basically created a local `.css` and ran it through stylelint to check to see what errored that way.

I think this is sufficient to add the requested functionality.

### CODE REVIEW

**Comment by dan-gamble** [comment]
After the CI, clearly not! Will look into what's failing it :)

**Comment by jeddy3** [comment]
> I'm not 100% sure how to get tape working...
1. Do a `npm install` to install the development dependencies
2. Do a `npm test` to run the tests (which is tape in this instance)

Hopefully that should work for you :)

**Comment by dan-gamble** [comment]
I did do that and i was just being stupid, the output just looked so foreign to me i figured it was broke, but after seeing it in Travis i realised it was just me being stupid :D Thanks though :)

**Comment by jeddy3** [comment]
>  but after seeing it in Travis i realised it was just me being stupid

Ha, I was same when seeing the Tape output for the first time too! :)

FYI, you're looking out for things like this...

``` bash
# 
css: "a {{ b {{ @media print { top: 0; }}}}}"
rule: statement-max-nesting-depth
options: 1, {"atRulesDontCount":true}
not ok 46 should pass
  ---
    operator: equal
    expected: 0
    actual:   1
    at: Test.<anonymous> (/home/travis/build/davidtheclark/stylelint-statement-max-nesting-depth/node_modules/stylelint-rule-tester/index.js:52:11)
  ...
# 
```

Which is saying we were expecting the rule to _not_ flag any warnings ("46 should pass...") against the CSS `a {{ b {{ @media print { top: 0; }}}}}`, but it did.

And...

``` bash
# 
css: "a { @media print { b { c { top: 0; }}}}"
rule: statement-max-nesting-depth
options: 1, {"atRulesDontCount":true}
not ok 51 should warn
  ---
    operator: equal
    expected: 1
    actual:   0
    at: Test.<anonymous> (/home/travis/build/davidtheclark/stylelint-statement-max-nesting-depth/node_modules/stylelint-rule-tester/index.js:76:11)
  ...
# 
```

Which is saying the opposite i.e. we were expecting the rule to flag a warning ("51 should warn...") against the CSS `a { @media print { b { c { top: 0; }}}}`, but it didn't.

**Comment by dan-gamble** [comment]
Thanks for the info :) It's defeated me for now and i'm just about to go for my company xmas meal but i'll revisit this tomorrow!

**Comment by jeddy3** [comment]
>  i'm just about to go for my company xmas meal

Have a good one :)

**Comment by dan-gamble** [comment]
Thanks :D

Sorry to be a bit of a pain but i am still kind of struggling with this :(

Would anyone be able to do a quick tl;dr on what this function does:

```
  function nestingDepth(node, level) {
    level = level || 0;

    if (node.parent.type === 'root') {
      return level;
    }

    if (
      node.parent.type === 'atrule'
      && (node.parent.parent.type === 'root' || options.atRulesDontCount)
    ) {
      return nestingDepth(node.parent, level);
    }

    if (node.parent.type === 'rule' && !node.parent.selector) {
      return nestingDepth(node.parent, level);
    }

    return nestingDepth(node.parent, level + 1);
  }
```

I'm trying to work out why things are based off the parent as opposed to the node itself, do things start at the deepest nest and bubble up from there? Or is the root the 1st child and each parent is 1 level down?

**Comment by dan-gamble** [comment]
Think i'm gonna have to admit defeat on this one :( I'm sure it's just a 4-5 liner but i've tried everything i can think and can't really get that far. Some things i try even change the number of tests there are somehow??

I looked at things like:

``` js
    if (node.parent.type === 'rule' && node.type === 'atrule') {
      return nestingDepth(node.parent, level);
    }
```

Just trying to basically ignore it if the actual node type is an `atrule` but not sure if that was the right line of thinking. Looking forward to the actual fix when it goes up to see where i was going wrong :)

**Comment by davidtheclark** [comment]
I'll take a look. Need to do a new release anyway for stylelint v3.

**Comment by dan-gamble** [comment]
Awesome, just updating my config to v3 atm, took me forever to notice the `plugins: {}` to `plugins: []` change :D

**Comment by davidtheclark** [comment]
Yeah, and the current plugins won’t work. :(

**Comment by davidtheclark** [comment]
I mean, until they're updated for v3

**Comment by dan-gamble** [comment]
Yea that's fine i'll just comment them out for now :) The only other one i want to use is the `selector-bem-pattern` and that looks updated so i'll try and incorporate that one after my config is updated

**Pull request closed without merging**
